// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalLayer: typeof import('./src/components/ModalLayer.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
  }
}

export { }
