// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Cell: typeof import('./src/components/Cell.vue')['default']
    CellRow: typeof import('./src/components/CellRow.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    ModalLayer: typeof import('./src/components/ModalLayer.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    NumberRange: typeof import('./src/components/NumberRange.vue')['default']
    ScoreBoard: typeof import('./src/components/ScoreBoard.vue')['default']
    ScoreCell: typeof import('./src/components/ScoreCell.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Share: typeof import('./src/components/Share.vue')['default']
    Stat: typeof import('./src/components/ScoreBoard.vue')['default']
    SwitchButton: typeof import('./src/components/SwitchButton.vue')['default']
  }
}

export { }
